trigger:
  branches:
    include:
      - main
      - develop
      - release/*
      - feature/*
  tags:
    include:
      - '*'

resources:
 repositories:
    - repository: Common_Pipelines
      type: git
      name: "PIPELINES.YML.AZ.ADO.cLD.983"
      ref: "refs/heads/develop"

extends:
  template: "imcsl-pipeline.yml@Common_Pipelines"
